version: '2'
services:
  biker-client:
    build: ./biker-client
    ports:
      - '3001:3001'
    depends_on:
      - server
  sender-client:
    build: ./sender-client
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
